// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCeBd0c8dt8B8xQdxm8QtjHPgHm-Pkx87c',
    appId: '1:817882007228:web:2a8c314b6cbeeb6563b2b9',
    messagingSenderId: '817882007228',
    projectId: 'gestionpaquetes2026',
    authDomain: 'gestionpaquetes2026.firebaseapp.com',
    storageBucket: 'gestionpaquetes2026.firebasestorage.app',
    measurementId: 'G-TGTMWGDQ3F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA18czaJyPEOXc9l9FAn-3eXKD61FVfhG8',
    appId: '1:817882007228:android:7340762d3b340b1d63b2b9',
    messagingSenderId: '817882007228',
    projectId: 'gestionpaquetes2026',
    storageBucket: 'gestionpaquetes2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA82pgbTKSVcMjztLa30FKXTTW248afX0s',
    appId: '1:817882007228:ios:f084a18fd31a14a063b2b9',
    messagingSenderId: '817882007228',
    projectId: 'gestionpaquetes2026',
    storageBucket: 'gestionpaquetes2026.firebasestorage.app',
    iosBundleId: 'com.example.gestionPaquetes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA82pgbTKSVcMjztLa30FKXTTW248afX0s',
    appId: '1:817882007228:ios:f084a18fd31a14a063b2b9',
    messagingSenderId: '817882007228',
    projectId: 'gestionpaquetes2026',
    storageBucket: 'gestionpaquetes2026.firebasestorage.app',
    iosBundleId: 'com.example.gestionPaquetes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCeBd0c8dt8B8xQdxm8QtjHPgHm-Pkx87c',
    appId: '1:817882007228:web:c9e2c0cf1e51ebe863b2b9',
    messagingSenderId: '817882007228',
    projectId: 'gestionpaquetes2026',
    authDomain: 'gestionpaquetes2026.firebaseapp.com',
    storageBucket: 'gestionpaquetes2026.firebasestorage.app',
    measurementId: 'G-NPK50LWW81',
  );
}
